config/routes.rb
Rails.application.routes.draw do
  get 'readers/new'
  get 'readers/create'
  get '/works', to: 'works#index'
  get '/home' , to: 'pages#home'
  devise_for :users
root 'pages#home'
  resources :works do
    resources :chapters
    resources :readers, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :work
end

app/models/reader.rb
class Reader < ApplicationRecord
    has_and_belongs_to_many :works
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy
end

app/models/work.rb
class Work < ApplicationRecord
    belongs_to :user 
    has_many :chapters, dependent: :destroy
    has_and_belongs_to_many :readers

    validates :cargo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
    def create
        @work = Work.find(params[:work_id])
        @chapter = @work.chapters.create(chapter_params)
        redirect_to work_path(@work)
    end

    private
    def chapter_params
        params.require(:chapter).permit(:chapter_number, :title, :summary)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  

  def create
    @work = Work.find(params[:work_id])
    @reader = @work.readers.create!(reader_params)
    redirect_to @work
  end
  
  def new
    @work = Work.find(params[:work_id])
    @reader = @work.readers.build
  end

  private

  def reader_params
      params.require(:reader).permit(:first_name, :last_name, :age, :comment)
  end  

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_work, only: %i[ show edit update destroy ]

  # GET /works or /works.json
  def index
    @works = Work.all
  end

  # GET /works/1 or /works/1.json
  def show
    @work = Work.find(params[:id])
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
    @work = Work.find(params[:id])
  end

  # POST /works or /works.json
  def create
      @work = current_user.works.build(work_params)

      respond_to do |format|
        if @work.save
          format.html { redirect_to work_url(@work), notice: "El cargo fue creado con éxito." }
          format.json { render :show, status: :created, location: @work }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @work.errors, status: :unprocessable_entity }
        end
      end
    end
   
  

  # PATCH/PUT /works/1 or /works/1.json
  def update
    @work = Work.find(params[:id])
    if @work.update(work_params)
      redirect_to @work
    else
      render :edit
    end
  end

  # DELETE /works/1 or /works/1.json
  def destroy
    work = Work.find(params[:id])
    work.destroy

    flash[:notice] = "El libro ha sido eliminado exitosamente"
    redirect_to works_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_params
      params.require(:work).permit(:cargo, :cantidad_vacantes, :description, :modalidad, :release_date, :rango_salarial, :region )
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>BolsaBootcamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="/assets/all.css" media="screen" rel="stylesheet" type="text/css" />
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>
  <body style="background-color:OldLace;">
  <br><br>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="col-12">
          <% if user_signed_in? %>
              <h2><b>Bienvenido: <%= current_user.email %>!!</b></h2>
              <%= link_to "Salir", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
              <div class="text-right"><%= link_to 'Postulaciones', works_path, class: 'btn btn-info btn-lg' %></div>
        </div>
            <% else %>
              <div>
                <nav class="navbar navbar-expand-sm bg-dark navbar-light">
                <ul class="navbar-nav">
                  <li class="nav-item active">
                  <%= link_to 'Home', home_path, class: 'btn btn-secondary'%>
                  </li>
                </ul>
                </nav> 
              </div>
            </div> 
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<br>
<div class="container">
    <div class="row">
        <div class="col-14">
            <hr>
            <div class='img-thumbnail text-center' style="margin-bottom:0">
              <%= image_tag "https://res.cloudinary.com/maravoly/image/upload/v1657297266/images/examen/BootCamp_xxxxxxxxxx_tmafof.png", style: 'height:20vw;width:40vw;'  %>
            </div><br>
            <h1>Bienvenidos!!!</h1>
            <hr>
            <div class="row">
              <div class="col-sm-6">
                <div class="card">
                  <div class="card-body">
                    <h2 style="text-align:center" class="text-dark"><strong>Empresa</strong></h2>
                    <div class='img-thumbnail text-center' style="margin-bottom:0">
                      <%= image_tag "https://res.cloudinary.com/maravoly/image/upload/v1657273025/images/examen/EMPRESA_nxqydh.png", style: 'height:20vw;width:30vw;' %>
                      </div> 
                    <p class="card-text">Lleva a tu empresa a otro nivel. Publica tus vacantes y opten al mejor candidato para tu empresa.</p>
                    <%= link_to "Registrarse", new_user_registration_path, class: 'btn btn-dark' %>
                    <%= link_to "Ingresar", new_user_session_path, class: 'btn btn-dark' %>
                  </div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="card">
                  <div class="card-body">
                    <h2 style="text-align:center" class="text-dark"><strong>Personas</strong></h2>
                    <div class='img-thumbnail text-center' style="margin-bottom:0">
                      <%= image_tag "https://res.cloudinary.com/maravoly/image/upload/v1657273030/images/examen/PERSONAS_jppwqu.png", style: 'height:20vw;width:30vw;'  %>
                      </div> 
                    <p class="card-text">¡Postula y entra rápido al mercado laboral! Aprende a programar con ayuda de nuestros tutores y encuentra trabajo rápidamente.</p>
                    <%= link_to "Registrarse", new_user_registration_path, class: 'btn btn-dark' %>
                    <%= link_to "Ingresar", new_user_session_path, class: 'btn btn-dark' %>
                  </div>
                </div>
              </div>
            </div>
            <br>
            <hr>
        </div>
        <br>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="media">
            <div class="media-body">
                <h3 class="display-4 text-info">SÚMATE A LA REVOLUCIÓN DIGITAL</h3><br>
                  <%= image_tag "https://res.cloudinary.com/maravoly/image/upload/v1657297611/images/examen/1_wntyxc.jpg", style: 'height:15vw;width:25vw;' %>
                  <%= image_tag "https://res.cloudinary.com/maravoly/image/upload/v1657297613/images/examen/2_o4pmn0.webp", style: 'height:15vw;width:20vw;' %>
                  <%= image_tag "https://res.cloudinary.com/maravoly/image/upload/v1657297608/images/examen/3_pm259j.png", style: 'height:15vw;width:25vw;' %><br><br>
                    <h3 class="display-5 text-info">/*Comunidad de aprendizaje*/</h3>
                    <p class="lead text-secondary">(‘ Generamos una comunidad que comparte sus experiencias y aprendizajes de manera desinteresada y honesta. Compartir conocimiento y experiencia es parte del proceso de aprendizaje ’);</p>
                    <h3 class="display-5 text-info">{ Tiempo }</h3>      
                    <p class="lead text-secondary"> (‘ ¡Aprovecha tu tiempo! Contamos con cursos intensivos y flexibles para que en un corto periodo puedas entrar al mercado laboral o desarrollar tus proyectos ’);</p>            
                    <h3 class="display-5 text-info">/*Aprende Haciendo*/</h3>              
                    <p class="lead text-secondary">(‘ Talleres 100% prácticos. Lo que aprendas, lo harás con las manos ocupadas. Aprende las herramientas del futuro, trabajando con ellas. Construye ese proyecto que estás pensando ’);</p>           
            </div>  
        </div>
    </div>
</div>
<div>
<%= image_tag "https://res.cloudinary.com/maravoly/image/upload/v1657299995/images/examen/te-esperamos-png_haxzql.webp"  %>
</div>
 <ul class="list-inline">
                        
                    <hr class="small">
                    <p class="text-muted">Copyright &copy; @maravoly 2022</p>

app/views/readers/create.html.erb
<h1>Readers#create</h1>
<p>Find me in app/views/readers/create.html.erb</p>

app/views/readers/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-10">
<h1>Postulación</h1>

    <%= form_with(model:[@work, @reader]) do |form| %>
        <div class="field">
            <%= form.label :nombre %>
            <%= form.text_field :first_name,  class:"form-control" %>
        </div>
    <br>
        <div class="field">
            <%= form.label :apellido %>
            <%= form.text_field :last_name %>
        </div>
    <br>
        <div class="field">
            <%= form.label :rut %>
            <%= form.number_field :rut %>
        </div>
    <br>
    <div class="field">
            <%= form.label :edad %>
            <%= form.number_field :age %>
        </div>
    <br>
    <div class="form-check" >
        <p>Género: 
    <select name="genero">
        <option>Femenino</option>
        <option>Masculino</option>
        <option>No especificar</option>
    </select>
        </p>
    </div>
    <br>
    <form action="../../form-result.php" method="post" enctype="multipart/form-data" target="_blank">
    <p>
        Subir Curriculum Vitae:
        <input type="file" name="pdf, .doc, .docx" accept="application/pdf, .doc, .docx"><br><br>
        <input type="submit" value="Enviar datos" class= 'btn btn-info mt-3'>
    </p>
    </form>   
    <% end %>
        </div>
    </div>
</div>
    <br>
    <br>
<%= link_to 'Back', works_path, class:"btn btn-secondary active" %>

app/views/works/_form.html.erb
<%= form_with(model: work) do |form| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
        <% work.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cargo %>
    <%= form.text_field :cargo %>
  </div>

  <div class="field">
    <%= form.label :cantidad_vacantes %>
    <%= form.text_field :cantidad_vacantes %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="form-check" >
    <p>Modalidad del Trabajo: 
   <select name="modalidad">
     <option>Remoto</option>
     <option>Presencial</option>
     <option>Mixto</option>
   </select>
    </p>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date %>
  </div>

  <div class="field">
    <%= form.label :rango_salarial %>
    <%= form.text_field :rango_salarial %>
  </div>

  <div class="field">
      <%#= form.collection_select(:region_id, Region.all, :id, :region, prompt: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editar Oferta de Trabajo</h1>
<%= form_for @work do |f| %>
  <div>
    <%= f.label :cargo %>
    <%= f.text_field :cargo, class:"form-group col-md-5 "%>
  </div>
  <div>
    <%= f.label :cantidad_vacantes %>
    <%= f.text_field :cantidad_vacantes, class:"form-group col-md-5" %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, class:"form-group col-md-5" %>
  </div>
  <div class="form-check" >
    <p>Modalidad del Trabajo: 
   <select name="modalidad">
     <option>Remoto</option>
     <option>Presencial</option>
     <option>Mixto</option>
   </select>
    </p>
  <div>
    <%= f.label :release_date %>
    <%#= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :rango_salarial %>
    <%= f.text_field :rango_salarial, step: :any, class:"form-group col-md-5" %>
  </div>
 <div class="field">
      <%#= form.collection_select(:region_id, Region.all, :id, :region, prompt: true) %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @work, class:"btn btn-success active" %> |
<%= link_to 'Back', works_path, class:"btn btn-secondary active" %>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div>
    <nav class="navbar navbar-expand-sm bg-secondary navbar-light">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Home', home_path, class: 'btn btn-dark'%>
        </li>
        <li class="nav-item">  
          <% if user_signed_in? %>
          <%= link_to 'Ingresar Nueva Oferta ', new_work_path, class: 'btn btn-info'%>
          <% end %>
        </li>
        <li class="nav-item">  
          <% if user_signed_in? %>
          <a class='btn btn-warning' href="http://localhost:3000/works/99/readers/new" target="_top">Postular</a>
          <% end %>
        </li>

      </ul>
    </nav>  
  </div>
  <div class="row">
    <div class="col-12"> 
<br>
<h1>Ofertas de Trabajo</h1>

<div class="table-responsive-lg">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Cargo</th>
      <th>Cantidad de Vacantes</th>
      <th>Descripción</th>
      <th>Modalidad</th>
      <th>Rango Salarial</th>
      <th>Fecha de Inicio</th>
      <th>Región</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><b><%= work.cargo %></b></td>
        <td><%= work.cantidad_vacantes %></td>
        <td><%= work.description %></td>
        <td><%= work.modalidad %></td>
        <%#= work.release_date %>
        <td><%= work.rango_salarial %></td>
        <%#= image_tag(url_for(work.region.flag_img)) %>
        <%#= image_tag region.image_url(:thumb) %>
        <% if user_signed_in? %>
        <td><%= link_to 'Ver', work, class: 'btn btn-outline-success' %></td>
        <% end %>
        <% if (user_signed_in? && (current_user == work.user)) %>
            <td><%= link_to 'Editar', edit_work_path(work), class: 'btn btn-outline-warning' %></td>
            <td><%= link_to 'Eliminar', work, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br><br>
    </div>
  </div>
</div>
<%= link_to 'Back', home_path, class:"btn btn-secondary active" %>

app/views/works/new.html.erb
<br><br>
<nav class="navbar navbar-expand-sm bg-secondary navbar-light">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Home', home_path, class: 'btn btn-secondary'%>
        </li>
      </ul>
</nav>
<div class="container">

<div class="row">
  <div class="col-6">
  
<br>
<h1>Nueva Oferta de Trabajo</h1>
<%= form_with model: Work.new do |f| %>

  <div class="form-check" >
    <%= f.label :cargo, "Puesto o Cargo" %>
    <%= f.text_field :cargo, class: 'form-control' %>
  </div>
  <br>
  <div class="form-check" >
    <%= f.label :cantidad_vacantes, "Cantidad de Vacantes" %>
    <%= f.number_field :cantidad_vacantes, step: :any, class: 'form-control' %>
  </div>
  <br>
  <div class="form-check" >
    <%= f.label :description, "Descripción" %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <br>
  <div class="form-check" >
    <p>Modalidad del Trabajo: 
   <select name="modalidad">
     <option>Remoto</option>
     <option>Presencial</option>
     <option>Mixto</option>
   </select>
    </p>
  </div>
  <br>
  <div class="form-check" >
    <%= f.label :release_date, "Fecha Inicio" %>
    <%#= f.date_field :release_date, class: 'form-control' %>
  </div>
  <br>
  <div class="form-check" >
    <%= f.label :rango_salarial, "Sueldo" %>
    <%= f.number_field :rango_salarial, step: :any, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
      <%#= form.collection_select(:region_id, Region.all, :id, :region, prompt: true) %>
  </div>
<br>
  <div class="form-check" >
    <%= f.submit "Crear Oferta", class: "btn btn-info mt-3" %>
  </div>
  <br>
<% end %>
</div>
  </div>
  </div>
<%= link_to 'Back', works_path, class:"btn btn-secondary active" %>

app/views/works/show.html.erb
<br><br>
<div class="container">
  <div class="row">
    <div class="col-12">
        <div>
            <nav class="navbar navbar-expand-sm bg-dark navbar-light">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <%= link_to 'Home', home_path, class: 'btn btn-secondary'%>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Editar', edit_work_path(@work), class: "btn btn-info" %>
                    </li>
                </ul>
            </nav> 
        </div>
<br>
<h1>Detalles de la Postulación</h1>
<hr>
<br>

<P>
<strong>Cargo:</strong>
<%= @work.cargo %>
</p>

<p>
<strong>Cantidad de Vacanes:</strong>
<%= @work.cantidad_vacantes %>
</p>

<p>
<strong>Descripción:</strong>
<%= @work.description %>
</p>

<p>
<strong>Modalidad:</strong>
<%= @work.modalidad %>
</p>

<p>
<strong>Rango Salarial:</strong>
<%= @work.rango_salarial %>
</p>

<p>
<strong>Región:</strong>
<%= @work.region %>
</p>

<br>
<hr>
<h4>Postular:</h4>

    <div>
        <% if @work.readers %>
        <% @work.readers.each do |reader|%>
        <strong><%= reader.id %>: 
        <p><b>Nombre:</b>  </strong><%= "#{reader.first_name} #{reader.last_name}" %>
        <br>
        <p><b>Comentario:</b>  </strong><%="#{reader.comment}"%></p>
        <% end %>
    </div>
    <% else %>
        <% 'No Readers Added!!!'%>
    <% end %>
<br>
<%= link_to 'Agregar Postulación', new_work_reader_path(@work) %>
<br><br>
<hr>
<h2>Listado de Postulantes:</h2>
<% @work.chapters.each do |chapter| %>
    <p>
        <strong>Nombre Completo:</strong>
        <%= chapter.chapter_number %>
    </p>

    <p>
        <strong>Cargo:</strong>
        <%= chapter.cargo %>
    </p>

    <p>
        <strong>Resumen:</strong>
        <%= chapter.summary%>
    </p>
<% end %>
<br>
<br>

<hr>
<h3>Agregue una Oferta:</h3>
<%= form_with model: [ @work, @work.chapters.build ] do |form| %>
    <p>
        <%= form.label :capítulo_número %><br>
        <%= form.number_field :chapter_number %>
    </p>
    <p>
        <%= form.label :título %><br>
        <%= form.text_field :cargo %>
    </p>
    <p>
        <%= form.label :resumen %><br>
        <%= form.text_area :summary %>
    </p>
    <p>
        <%= form.submit "Crear Oferta Nueva"%>
    </p>
<% end %>
<br><br>
<%= link_to 'Back', works_path, class:"btn btn-secondary active" %>